### PR TITLE
Adds .gitignore to template

### PR DESCRIPTION
**Pull request by petems**
:+1:

### CODE REVIEW

**Comment by logicminds** [comment]
In order for this to be created you will need to add a new method that uses the erb file to create it.
example:
```ruby
def safe_create_gemfile(template='gemfile.erb')
    safe_create_template_file('Gemfile', template)
  end
```
Additionally, you would have to call method to create the resource.
https://github.com/logicminds/puppet-retrospec/blob/master/lib/retrospec.rb#L42

Also rename the ignore file to end in erb.

**Comment by petems** [comment]
Ok, will fix! :+1:

**Comment by logicminds** [comment]
@petems actually I just implemented #12 which would allow you to just add the file like in the original pull request.  So don't change a think.  (should push new code later today)

**Comment by logicminds** [comment]
thanks @petems

**Pull request merged**
